### PR TITLE
mixin changes for cts aaos14 sensors

### PR DESCRIPTION
**Pull request by RajaniRanjan**
addition required sensors xml files for automotive

providing specific permission for automotive sensors.

Tracked-On: OAM-118145
Signed-off-by: RajaniRanjan <rajani.ranjan@intel.com>

### CODE REVIEW

**Review by balajim001 — APPROVED** [review]
LGTM

**Comment by RajaniRanjan** [comment]
> It is not permission where as we are enabling the feature by providing feature file. Please update the commit message accordingly.

done

**Review by vilasrk — APPROVED** [review]
LGTM

**Review by balajim001 — APPROVED** [review]
LGTM

**Pull request merged**
