### PR TITLE
ASB - Security Patch integration August 2023

### PR DESCRIPTION
**Pull request by alavalas1**
ASB -Security Patch integration August 2023

Changes include:
-Removal of patches causing conflict as those
are present in the code base.
-Addition of ASB-August-2023 patches

Tracked-On: OAM-111362
Signed-off-by: Reddy, Alavala Srinivasa <alavala.srinivasa.reddy@intel.com>

### CODE REVIEW

**Review by tanujtekriwal — APPROVED** [review]
LGTM

**Review by tanujtekriwal — APPROVED** [review]
LGTM

**Review by kaushlen — APPROVED** [review]

**Review by shyjumon-n — APPROVED** [review]
Google security patch integration.
LGTM

**Review by JeevakaPrabu — CHANGES_REQUESTED** [review]
Commit message needs rewrite

**Review by JeevakaPrabu — APPROVED** [review]

**Pull request merged**
