### PR TITLE
ASB-April 2024 Security Patches integration

### PR DESCRIPTION
**Pull request by AlamIntel**
Integrating Google Android Security Bulletin Patches

Test done: STS r25 TCs Passed

Tracked-On: OAM-116786

### CODE REVIEW

**Review by tanujtekriwal — APPROVED** [review]
LGTM

**Review by shyjumon-n — CHANGES_REQUESTED** [review]
Update the commit msg like below:
"Integrating Google Android Security Bulletin Patches"

**Review by shyjumon-n — APPROVED** [review]
LGTM

**Review by tanujtekriwal — APPROVED** [review]
LGTM

**Review by shyjumon-n — APPROVED** [review]
LGTM

**Pull request merged**
