### PR TITLE
camera fix uvc cameraid numberofcamera issue

### PR DESCRIPTION
**Pull request by shivasku82**

### CODE REVIEW

**Comment by neofang7** [comment]
LGTM

**Review by balajim001 — APPROVED** [review]
LGTM

**Review by neofang7 — APPROVED** [review]
LGTM.

**Review by JeevakaPrabu — CHANGES_REQUESTED** [review]
Sorry, what's the actual code change?

**Review by JeevakaPrabu — CHANGES_REQUESTED** [review]
commit message not in sync with the actual change. Please provide a commit message that calls out that patch file path change

**Pull request merged**
