### PR TITLE
Allow sensor domain to use tcp_socket

### PR DESCRIPTION
**Pull request by JaikrishnaNemallapudi**
Tracked-On: OAM-97787
Signed-off-by: Jaikrishna Nemallapudi <nemallapudi.jaikrishna@intel.com>

### CODE REVIEW

**Comment by balajim001** [comment]
Please help provide patch description

**Review by balajim001 — APPROVED** [review]
LGTM

**Review by swaroopbalan — APPROVED** [review]

**Review by JeevakaPrabu — APPROVED** [review]
Please work with @shyjumon-n to upstream the changes

**Review by shyjumon-n — APPROVED** [review]
Looks Good to me.

**Pull request merged**
