### PR TITLE
Fix javacrash on com.android.gallery3d as CursorIndexOutOfBoundsExcep…

### PR DESCRIPTION
**Pull request by XuBing0**
…tion

Media file is not exist on the path, so the cursor of the path is not null but the size is zero, so need check both.

Tracked-On: OAM-113164

### CODE REVIEW

**Review by tanujtekriwal — COMMENTED** [review]
Hi Bing,
We are now following Commit message format:

Commit header

Commit Explanation

Test: <To test the fix>

Tracked-On:
Signed-Off-By:


Please align your commit message to same.

**Review by shyjumon-n — APPROVED** [review]
LGTM

**Review by dyang23 — APPROVED** [review]
LGTM

**Review by shyjumon-n — APPROVED** [review]
LGTM

**Pull request merged**
