### PR TITLE
Fix audio mixer playback for mono source.

### PR DESCRIPTION
**Pull request by haochuan1982**
Fix audio mixer playback for mono source

Fix audio playback for mono audio source, when audio hal support multi channel output.

Tracked-On: OAM-111131

### CODE REVIEW

**Comment by haochuan1982** [comment]
recheck

**Review by gkdeepa — APPROVED** [review]
LGTM

**Comment by xinxin-wan** [comment]
⁠could you please try MIXTYPE_MULTI_SAVEONLY instead of MIXTYPE_MULTI_SAVEONLY_MONOVOL, since MIXTYPE_MULTI_SAVEONLY_MONOVOL will not only save audio data and but also volume information for mono？

**Comment by haochuan1982** [comment]
> ⁠could you please try MIXTYPE_MULTI_SAVEONLY instead of MIXTYPE_MULTI_SAVEONLY_MONOVOL, since MIXTYPE_MULTI_SAVEONLY_MONOVOL will not only save audio data and but also volume information for mono？

MIXTYPE_MULTI_SAVEONLY is target for stereo output case, for multi channel output, it will trigger assert. Please check this 
audiomixerOps.h, function volumeMulti
            } else if constexpr (MIXTYPE == MIXTYPE_MULTI_SAVEONLY) {
                static_assert(NCHAN <= 2);
                for (int i = 0; i < NCHAN; ++i) {
                    *out++ = MixMulAux<TO, TI, TV, TA>(*in++, vol[i], &auxaccum);
                }

**Review by JeevakaPrabu — APPROVED** [review]

**Comment by haochuan1982** [comment]
> ⁠could you please try MIXTYPE_MULTI_SAVEONLY instead of MIXTYPE_MULTI_SAVEONLY_MONOVOL, since MIXTYPE_MULTI_SAVEONLY_MONOVOL will not only save audio data and but also volume information for mono？

**Comment by haochuan1982** [comment]
> > ⁠could you please try MIXTYPE_MULTI_SAVEONLY instead of MIXTYPE_MULTI_SAVEONLY_MONOVOL, since MIXTYPE_MULTI_SAVEONLY_MONOVOL will not only save audio data and but also volume information for mono？
> 
> MIXTYPE_MULTI_SAVEONLY is target for stereo output case, for multi channel output, it will trigger assert. Please check this audiomixerOps.h, function volumeMulti } else if constexpr (MIXTYPE == MIXTYPE_MULTI_SAVEONLY) { static_assert(NCHAN <= 2); for (int i = 0; i < NCHAN; ++i) { *out++ = MixMulAux<TO, TI, TV, TA>(*in++, vol[i], &auxaccum); }

**Review by gkdeepa — APPROVED** [review]
LGTM

**Review by JeevakaPrabu — APPROVED** [review]

**Pull request merged**
