### PR TITLE
ASB-OCT 2024 Security Patches integration

### PR DESCRIPTION
**Pull request by AlamIntel**
Integrating Google Android Security Bulletin Patches

Test done: STS r31 TCs Passed.

Tracked-On: OAM-125330

### CODE REVIEW

**Review by ceiba1985 — APPROVED** [review]

**Review by dyang23 — APPROVED** [review]
LGTM

**Review by shyjumon-n — CHANGES_REQUESTED** [review]
This should not be merged now as beta is in progress in U MR0 core and only merge on first week of every month as a Candance.

**Comment by AlamIntel** [comment]
Sure @shyjumon-n,
created PR to build EB, STS Test need to be done. 
Thank you.

**Review by tanujtekriwal — APPROVED** [review]
LGTM

**Review by shyjumon-n — APPROVED** [review]
LGTM

**Pull request merged**
