### PR TITLE
Fix for Build Failure in SystemUI TestCase.

### PR DESCRIPTION
**Pull request by ankithbti52509**
Corrected syntax.

Tracked-On: OAM-108579

### CODE REVIEW

**Review by shyjumon-n — APPROVED** [review]
LGTM

**Review by shyjumon-n — APPROVED** [review]
LGTM

**Review by tanujtekriwal — APPROVED** [review]
LGTM

**Comment by ankithbti52509** [comment]
No Longer Required with ASOP r43.

**Pull request closed without merging**
