### PR TITLE
Integrate JUNE-2022 ASB patches to R- stable branch

### PR DESCRIPTION
**Pull request by rrsenapati1**
Tracked-On: OAM-102322
Signed-off-by: Senapati, Rasmiranjan <rasmiranjan.senapati@intel.com>

### CODE REVIEW

**Review by tanujtekriwal — COMMENTED** [review]
Are all the deleted patches actually deleted in ASB?
Like sqlite i see 2 patches and 2 others.

**Comment by rrsenapati1** [comment]
> 

those patches are already applied

**Comment by tanujtekriwal** [comment]
> > 
> 
> those patches are already applied

All 4 looks like ASB patches only and no AOSP rebase has happened recently i think. How come they are showing as already applied now? 
Or was it already like that earlier and it is getting cleaned up now?

**Comment by rrsenapati1** [comment]
> > > 
> > 
> > 
> > those patches are already applied
> 
> All 4 looks like ASB patches only and no AOSP rebase has happened recently i think. How come they are showing as already applied now? Or was it already like that earlier and it is getting cleaned up now?

I'm not sure. I checked the codebase it's already applied. I've mentioned the commits on excel sheet

**Review by tanujtekriwal — APPROVED** [review]
LGTM

**Review by shyjumon-n — APPROVED** [review]
Google security patch integration. 
LGTM

**Pull request merged**
