### PR TITLE
ASB - Security Patch integration to 12.1

### PR DESCRIPTION
**Pull request by alavalas1**
We ported the ASB Patches from 2022-07-01 to 2023-07-01.
    As present, We are not updating the Security_patch_level from 2022-06-05 to 2023-07-01.
    Due to observed the STS-r16 test cases are failure-3 Numbers,
    Once resolved the STS failure, we update the  Security_patch_level.
    
    STS failure in the test case details
    1)x86_64 CtsPermission4TestCases
        a)android.permission4.cts.CameraMicIndicators PermissionTest#testMicIndicatorWithManualFinishOpStillShows
    2)x86_64 CtsSecurityTestCases
        a)android.security.cts.ActivityManager Test#testActivityManager_stripTransitionFromActivityOptions
        b)android.security.cts.AudioSecurityTest #testVisualizerCapture_CVE_2017_0396

### CODE REVIEW

**Review by tanujtekriwal — APPROVED** [review]
LGTM

**Comment by tanujtekriwal** [comment]
October 22, December 22, March 23, April 23 - > There are NO ASB or all patches already there?

**Review by tanujtekriwal — COMMENTED** [review]
Please check and reply my comment before merge.

**Comment by alavalas1** [comment]
> October 22, December 22, March 23, April 23 - > There are NO ASB or all patches already there?

>October 22, December 22, March 23, April 23 - > All patches are already present in the codebase

**Review by shyjumon-n — APPROVED** [review]
Google security patch integration.
LGTM

**Pull request merged**
