### PR TITLE
Set audio volume to maximum

### PR DESCRIPTION
**Pull request by padmashree9110**
Sets all audio stream volumes to maximum
Tracked-On: OAM-99971
Signed-off-by: pmandri <padmashree.mandri@intel.com>

### CODE REVIEW

**Review by gkdeepa — APPROVED** [review]
LGTM, this is a WA for cfc based on customer request to provide complete control to host and set the guest volume to max.

**Review by shyjumon-n — APPROVED** [review]
Looks Good to me

**Review by gkdeepa — APPROVED** [review]
LGTM, this is a WA for cfc based on customer request to provide complete control to host and set the guest volume to max.

**Review by gkdeepa — APPROVED** [review]
LGTM, this is a WA for cfc based on customer request to provide complete control to host and set the guest volume to max.

**Review by shyjumon-n — APPROVED** [review]
LGTM.

**Pull request merged**
