### PR TITLE
Remove composer3 hal diff patches

### PR DESCRIPTION
**Pull request by manxiaoliang**
Putting it to drm-hwcomposer master repo.

Tracked-On: OAM-118438

### CODE REVIEW

**Comment by iViggyPrabhu** [comment]
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

**Comment by iViggyPrabhu** [comment]
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

**Comment by iViggyPrabhu** [comment]
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

**Comment by iViggyPrabhu** [comment]
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

**Review by zhy1030 — APPROVED** [review]

**Pull request merged**
