### PR TITLE
Porting the diff to caas_dev

### PR DESCRIPTION
**Pull request by swaroopbalan**

### CODE REVIEW

**Review by shyjumon-n — APPROVED** [review]
Place holders. LGTM

**Review by shyjumon-n — APPROVED** [review]
LGTM

**Comment by iViggyPrabhu** [comment]
Merged as part of, https://buildbot.sh.intel.com/absp/builders/celadon-mergerequest/builds/3229

**Comment by iViggyPrabhu** [comment]
Merged as part of /absp/builders/celadon-mergerequest/builds/3229

**Pull request merged**
