### PR TITLE
Expand audio framework max channel count to 24

### PR DESCRIPTION
**Pull request by haochuan1982**
Update FCC_LIMIT to FCC_24 for audio 16 channel user case

Tracked-On: OAM-110582

### CODE REVIEW

**Comment by haochuan1982** [comment]
@gkdeepa , @dyang23  , @xinxin-wan, @libinyang update patch to projectceladon. Please review

**Review by dyang23 — APPROVED** [review]
LGTM

**Review by gkdeepa — APPROVED** [review]
LGTM

**Review by gkdeepa — APPROVED** [review]
LGTM

**Review by gkdeepa — APPROVED** [review]
LGTM

**Review by gkdeepa — APPROVED** [review]
LGTM

**Review by gkdeepa — APPROVED** [review]
LGTM

**Comment by xinxin-wan** [comment]
LGTM

**Review by JeevakaPrabu — APPROVED** [review]

**Pull request merged**
